use_frameworks!

platform :ios, '9.0'

target 'CJCarouselView_Example' do
  pod 'CJCarouselView', :path => '../'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'FLEX'
  target 'CJCarouselView_Tests' do
    inherit! :search_paths

    
  end
end
