use_frameworks!

platform :ios, '11.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

target 'CJCarouselView_Example' do
  pod 'CJCarouselView', :path => '../'
  pod 'CJCollectionViewAdapter'
  pod 'CJCollectionViewAdapter/Cell'
  pod 'SDWebImage', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true
  pod 'Toast', :inhibit_warnings => true
  pod 'FLEX', :inhibit_warnings => true
  pod 'FTIndicator/FTProgressIndicator', :inhibit_warnings => true
  target 'CJCarouselView_Tests' do
    inherit! :search_paths
  end
end
